<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Create' => '',
    'Create Person' => '',
    'Created At' => '',
    'Delete' => '',
    'E-mail' => '',
    'Email' => '',
    'ID' => '',
    'Last Visit' => '',
    'Messenger' => '',
    'Notify About' => '',
    'Pass Hash' => '',
    'Password' => '',
    'Password Reset Token' => '',
    'Pemember now' => '',
    'People' => '',
    'Remember login and password' => '',
    'Repeat password' => '',
    'Status' => '',
    'Type Notify' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Username' => '',
    'Username (!!!not email)' => '',
    'Verify captcha code:' => '',
];
